Repository sparta-BlackYolk/black-yolk, pull requests merged in 2024-12, with the labels that each got.

#47 [FEATURE] Delivery 패키지 생성 및 DTO & Entity & Repository 작성
  delivery-service/.gitignore
  delivery-service/build.gradle
  delivery-service/src/main/java/com/sparta/blackyolk/delivery_service/application/dto/request/DeliveryCreateRequestDto.java
  delivery-service/src/main/java/com/sparta/blackyolk/delivery_service/application/dto/request/DeliveryRouteCreateRequestDto.java
  delivery-service/src/main/java/com/sparta/blackyolk/delivery_service/application/dto/response/DeliveryResponseDto.java
  delivery-service/src/main/java/com/sparta/blackyolk/delivery_service/application/dto/response/DeliveryRouteResponseDto.java
  delivery-service/src/main/java/com/sparta/blackyolk/delivery_service/domain/model/BaseEntity.java
  delivery-service/src/main/java/com/sparta/blackyolk/delivery_service/domain/model/CurrentStatus.java
  delivery-service/src/main/java/com/sparta/blackyolk/delivery_service/domain/model/Delivery.java
  delivery-service/src/main/java/com/sparta/blackyolk/delivery_service/domain/model/DeliveryRoute.java
  delivery-service/src/main/java/com/sparta/blackyolk/delivery_service/domain/repository/DeliveryRepository.java
  delivery-service/src/main/java/com/sparta/blackyolk/delivery_service/domain/repository/DeliveryRouteRepository.java
  delivery-service/src/main/java/com/sparta/blackyolk/delivery_service/infrastructure/repository/DeliveryJpaRepository.java
  delivery-service/src/main/java/com/sparta/blackyolk/delivery_service/infrastructure/repository/DeliveryRepositoryImpl.java
  delivery-service/src/main/java/com/sparta/blackyolk/delivery_service/infrastructure/repository/DeliveryRouteJpaRepository.java
  delivery-service/src/main/resources/application-key.yml
  delivery-service/src/main/resources/application.properties
  delivery-service/src/main/resources/application.yml
  order-service/.gitignore
Labels: enhancement

#55 [Chore] gateway test application 설정 파일 수정
  gateway/src/main/resources/application.yml
Labels: enhancement

#67 [Test] hubroute 최단 경로 조회를 위한 test 데이터 생성
  logistic-service/hubv4.sql
Labels: documentation, enhancement

#76 [Bug] 예외 처리 세부 내용 수정
  logistic-service/src/main/java/com/sparta/blackyolk/logistic_service/common/exception/ErrorCode.java
  logistic-service/src/main/java/com/sparta/blackyolk/logistic_service/hub/application/service/HubService.java
  logistic-service/src/main/java/com/sparta/blackyolk/logistic_service/hubroute/application/service/HubRouteService.java
Labels: bug

#79 [Add] UserClient override 추가
  logistic-service/src/main/java/com/sparta/blackyolk/logistic_service/common/fallback/UserClientFallbackFactory.java
Labels: enhancement

#83 [#82] [Refactor] Hub 생성 및 수정 시 파라미터에 토큰 제거
  logistic-service/src/main/java/com/sparta/blackyolk/logistic_service/common/fallback/UserClientFallbackFactory.java
  logistic-service/src/main/java/com/sparta/blackyolk/logistic_service/common/feignclient/UserClient.java
  logistic-service/src/main/java/com/sparta/blackyolk/logistic_service/common/service/UserService.java
  logistic-service/src/main/java/com/sparta/blackyolk/logistic_service/hub/application/domain/HubForCreate.java
  logistic-service/src/main/java/com/sparta/blackyolk/logistic_service/hub/application/domain/HubForUpdate.java
  logistic-service/src/main/java/com/sparta/blackyolk/logistic_service/hub/application/service/HubService.java
  logistic-service/src/main/java/com/sparta/blackyolk/logistic_service/hub/framework/web/controller/HubCommandController.java
  logistic-service/src/main/java/com/sparta/blackyolk/logistic_service/hub/framework/web/dto/HubCreateRequest.java
  logistic-service/src/main/java/com/sparta/blackyolk/logistic_service/hub/framework/web/dto/HubUpdateRequest.java
Labels: bug, enhancement
